version : '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcabc123

  web:
    build : .
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    environment:
      POSTGRES: postgres
      POSTGRES_DB: demodb
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: abcabc123

  frontend:
    build: ./demoAjs
    ports:
      - "4200:80"

